"""Add subcategory_id to Product

Revision ID: 491f8028c92c
Revises: e3debeb48473
Create Date: 2025-03-30 21:06:07.414464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491f8028c92c'
down_revision = 'e3debeb48473'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategory_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uix_product_supplier', ['product_name', 'supplier_id'])
        batch_op.create_foreign_key(None, 'subcategories', ['subcategory_id'], ['subcategory_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uix_product_supplier', type_='unique')
        batch_op.drop_column('subcategory_id')

    # ### end Alembic commands ###
