"""Fixed order and order_details model

Revision ID: 5b90f08b63e6
Revises: 419025f75e71
Create Date: 2025-03-11 12:52:28.500822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b90f08b63e6'
down_revision = '419025f75e71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_details', schema=None) as batch_op:
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###
